"""add doc_id in documents

Revision ID: e8f92ebe3c57
Revises: 018bc3460336
Create Date: 2026-09-05 18:08:56.343070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8f92ebe3c57'
down_revision: Union[str, Sequence[str], None] = '018bc3460336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_unique_constraint('uq_documents_doc_id', ['doc_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_documents_doc_id', type_='unique')
        batch_op.drop_column('doc_id')
    # ### end Alembic commands ###
